Neos:
  Fusion:
    defaultContext:
      Archivist: 'PunktDe\Archivist\Eel\ArchivistHelper'

  ContentRepositoryRegistry:
    presets:
      'default':
        commandHooks:
          'PunktDeArchivistArchivistCommandHookFactory':
            factoryObjectName: PunktDe\Archivist\CommandHook\ArchivistCommandHookFactory

PunktDe:
  Archivist:
    sortingInstructions: []
